### ISSUE TITLE
provide helpers for setting custom defaults for flags and options

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/goose#105]
It's currently possibly to [set a default hostname](https://docs.rs/goose/*/goose/struct.GooseAttack.html#method.set_host) for the load test, removing the requirement to call `--host=` when running from the command line (unless you want to override the default). 

It should be possible to do this for most all CLI options. This offers a few advantages, including: 1) you can hand a compiled and fully configured load-test to a team to run without the need of explaining to them how to set a complicated assortment of flags and options, 2) when controlling Goose from another application (for example a UI) you may not even be invoking the tool from the command line.

So in addition to [`.set_host()'](), we'd also have `.set_users()`, `.set_hatch_rate()`, etc ...  And as with set_host, it would be a default that could be overridden by invoking the appropriate command line option/flag.

**Comment by LionsAd** [comment]
.set_option — please - this gets messy else

**Comment by JordiPolo** [comment]
FWIW, I [just set the values](https://github.com/JordiPolo/minos/blob/master/src/performance.rs#L16-L26) in the GooseConfiguration struct.

**Comment by jeremyandrews** [comment]
Yes, we do that in tests as well. The goal of this task is to set up an order of precedence where load tests can define defaults that can be overridden from the command line.

Perhaps it should be named `.set_default()` to make this more clear.

**Comment by jeremyandrews** [comment]
implemented in #153
