### ISSUE TITLE
also optionally provide per-task-function statistics

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/goose#107]
Currently statistics are per-request. With #103 tasks return a Result() giving us insight into how often the entire Task succeeds and/or fails. This issue is to optionally provide statistics about this at the end of a load test.

One specific use-case of this feature would be to confirm that all task sets have been assigned to a `GooseUser`, and that all contained tasks have actually run. These statistics would provide insight into how often each Task is running, and whether any were skipped (ie, due to weighting and too few users).

**Comment by LionsAd** [comment]
I like that a lot - this is so useful
