### ISSUE TITLE
Options for running statistics and summary statistics

### ISSUE THREAD

**Issue by JordiPolo** [tag1consulting/goose#115]
Currently stats are enabled or disabled "globally". Either the running statistics every 15seconds and the final summary both appear or if disabled neither appear.
In my use-case I love the final statistics but pretty much want to get rid of the running statistics but it is not possible. All the structs are also private so can't do much from there either.

**Comment by jeremyandrews** [comment]
To disable running stats, enable the `--only-summary` flag:
```
        --only-summary     Only prints summary stats
```

The structs being private is an oversight, the intent is that after a load test you can either display the information using the built in `.display()` helper, or process it yourself in your code (or both).

**Comment by JordiPolo** [comment]
Sorry, yes I totally did not see that one. I think this is covered then so I'm closing this issue. Thanks for the fast response!
