### ISSUE TITLE
[BUG] Gaggle test fails if running `cargo test`

### ISSUE THREAD

**Issue by LionsAd** [tag1consulting/goose#121]
Observed behavior: Gaggle test fails if running `cargo test`
Wanted behavior: Gaggle test is `skipped` if running `cargo test` (without --all-features)

**Comment by jeremyandrews** [comment]
My concern with skipping the gaggle test is that it provides a path for tests to pass with code actually broken. I tell cargo which test to run if I'm only repeatedly re-testing a non-gaggle feature (ie https://stackoverflow.com/questions/54585804/how-to-run-a-specific-unit-test-in-rust).

`cargo test` tells Cargo to run all tests, and IMO it should fail if the gaggle feature is not enabled, as gaggles are broken if you don't compile in `nng`.

**Comment by jeremyandrews** [comment]
We need to review how other Rust projects are handling this.
