### ISSUE TITLE
TLS client cert support 

### ISSUE THREAD

**Issue by aidylewis** [tag1consulting/goose#154]
Would it be possible for TLS client cert support for requests made for non-live environments?

**Comment by jeremyandrews** [comment]
Goose is currently using Reqwest for all client requests, so you'd need to refer to the [Reqwest documentation](https://docs.rs/reqwest/*/reqwest/struct.ClientBuilder.html).

See the `GooseUser` [`set_client_builder()` method](https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#method.set_client_builder) documentation to see how to set up a custom configuration.
