### ISSUE TITLE
Make it possible to manipulate cookies directly (e.g. clear a session or add one special cookie)

### ISSUE THREAD

**Issue by LionsAd** [tag1consulting/goose#231]

**Comment by jeremyandrews** [comment]
I believe this is already possible through the Reqwest client. See the documentation which currently provides examples for setting a custom user agent and custom headers:
https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#method.set_client_builder

I think this issue just needs more examples in the documentation, specifically around working with cookies in the client.
