### ISSUE TITLE
Create an HTML report

### ISSUE THREAD

**Issue by LionsAd** [tag1consulting/goose#232]

**Comment by LionsAd** [comment]
Note: Think about which libraries to use and what to "ship" with goose.

**Comment by kazimir-malevich** [comment]
I am currently looking at the [Influx](https://www.influxdata.com/) stack and reading the CSV metric output with [Flux](https://www.influxdata.com/products/flux/) and piping into InfluxDB and visualising either through [Telegraf](https://www.influxdata.com/time-series-platform/telegraf/) or Grafana. I estimate that this will be done by the end of next week.
