### ISSUE TITLE
add charts to HTML report

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/goose#246]
The `--report-file` option already generates an HTML report with the same information found on the CLI when running Goose. It should be enhanced to also include useful charts to visualize the load test.

A continuation of #232

**Comment by slashrsm** [comment]
#381 Added first graphs, but there are more tasks that we need to do:

- Confirm that metrics are correct (when throttling is enabled RPS numbers do not match exactly)
- Automated tests
- Add additional graphs.
