### ISSUE TITLE
How can I retrieve and use data that is returned in a response body?

### ISSUE THREAD

**Issue by bwelch0581** [tag1consulting/goose#249]
I have a series of POST requests that I want to run subsequent to each other. When I send the first POST request, its response body contains data that needs to be used in subsequent POST requests. How can I use Goose to accomplish this goal? For example, an ID is created in the first POST request that I want to use in another POST request that should be ran next, as part of a larger test scenario that I want to load test against. I would like this capture of data from the response body be done as a part of the original load test of the POST requests (instead of having to have a separate request just to capture the data from the response body).

**Comment by jeremyandrews** [comment]
You'll need to make multiple requests in the same task. Goose returns the response from each POST, so you just need to extract what you need from that response. I tend to use regex whenever possible as it's very fast, but you can also use a more complex library to walk the dom and extract things based on classes or ids.

For example (while not a POST here, it works the same) see our first request here:
https://github.com/tag1consulting/goose/blob/main/examples/umami/admin.rs#L22

We extract the response body here:
https://github.com/tag1consulting/goose/blob/main/examples/umami/admin.rs#L33

We extract `form_build_id` here:
https://github.com/tag1consulting/goose/blob/main/examples/umami/admin.rs#L51

We use the extracted `form_build_id` in our subsequent POST here:
https://github.com/tag1consulting/goose/blob/main/examples/umami/admin.rs#L65

**Comment by jeremyandrews** [comment]
@bwelch0581 Were you able to get this working? Can this issue be closed?

**Comment by jeremyandrews** [comment]
Closing this through lack of response. Feel free to re-open if you've just not had time to dig in any further.
