### ISSUE TITLE
bind ip or port in rust file

### ISSUE THREAD

**Issue by universon123** [tag1consulting/goose#275]
Hi:
  why does not work below?
        .set_default(GooseDefault::ManagerHost, "127.0.0.1")?
        .set_default(GooseDefault::ManagerPort, 8089)?
is there another way to bind ip or port in rust file?
finally,how to add headers below?
let request_builder = user.goose_post("/opt/").await?;
thanks!

**Comment by jeremyandrews** [comment]
Where is the rest of your code? You can see an example of using `.set_default()` here:
https://github.com/tag1consulting/goose/blob/c3eb66ee8095ca854499e78e662be0407915fba0/examples/umami/main.rs#L83

And the full documentation is here, with more examples:
https://docs.rs/goose/0.11.1/goose/trait.GooseDefaultType.html

What are the errors you're running into? What you describe will work if you do it in the correct place.

For an example of adding headers, see the documentation here and the example included:
https://docs.rs/goose/0.11.1/goose/goose/struct.GooseUser.html#method.set_client_builder

**Comment by universon123** [comment]
i don't want to run main.rs file at cmd line by --host, how to set destination ip and destination port if i don't have a dns address？
by function setup_custom_client,i now kown how to set headers,but i don't kown how to send post request?
Thanks for your  help and patience!

**Comment by jeremyandrews** [comment]
If your goal is to set a default host (and avoid having to type `--host` from the command line), then you want to do the same thing that is done in the `umami` example linked above. You can include the port in the URL. For example, something like this:

```rust
fn main() -> Result((), GooseError> {
    let _goose_metrics = GooseAttack::initialize()?
        // See included examples and documentation for how to create tasks and tasksets
        .register_taskset(taskset!("Build your taskset w/ tasks here")
        )
        // Here is where you can define a custom host and port to load test against
        .set_default(GooseDefault::Host, "http://example.com:8089/")?
        .execute()?
        .print();

    Ok(())
}
```

Here's a couple of examples of how to send a POST:
- https://github.com/tag1consulting/goose/blob/c3eb66ee8095ca854499e78e662be0407915fba0/examples/simple.rs#L44
- https://github.com/tag1consulting/goose/blob/c3eb66ee8095ca854499e78e662be0407915fba0/examples/umami/common.rs#L573

Also, please refer to the documentation:
- https://docs.rs/goose/0.11.1/goose/goose/struct.GooseUser.html#method.goose_post

If this isn't working, please provide an example of what you're trying to do, or at least the errors you're running into.

**Comment by jeremyandrews** [comment]
(BTW: the ManagerHost and ManagerPort that you were configuring before was for building a distributed load test, or Gaggle. Some background here: https://www.tag1consulting.com/blog/using-gaggles-distribute-your-load-testing and an example of how it works here: https://www.tag1consulting.com/blog/show-me-how-flock-flies-working-gaggle-goose -- those options simply define the host and port that the Manager listens for Workers on, and doesn't affect the host that the load test runs against.)

**Comment by jeremyandrews** [comment]
No further feedback, closing. Feel free to re-open if this is still a question to you and not answered in my above replies. Or open a new issue if you have followups.
