### ISSUE TITLE
Doc: Coordinated Omission vulnerability

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#277]
Thank you for the effort that has gone into goose and for making it open source.

We are looking into load testing tools, ideally we'd like to use Rust based tool for the performance and stability head room provided by Rust.  That seems to mean Drill or Goose.

Could you say something in your docs about vulnerability of Goose to coordinated omission errors/bias?

**Comment by jeremyandrews** [comment]
Can you provide more detail on what you're looking for? Perhaps provide an example of another load testing framework that supplies similar documentation? It's not clear to me what you're after.

Offhand: Goose is simply a framework on which you can build a load test. You're responsible for building the proper load testing plans that simulate your desired load appropriately.

**Comment by bbros-dev** [comment]
> Perhaps provide an example of another load testing framework that supplies similar documentation

Sure, I think this is what you were after? 
https://github.com/giltene/wrk2#wrk2

> Goose is simply a framework on which you can build a load test.

Understood, but is it the user responsibility to handle generating the timing at which requests are made, and how response times are stored, etc., etc.

**Comment by jeremyandrews** [comment]
Goose records the actual response times from when a request is made to when the response returns. As such, it is definitely "CO vulnerable". 

Here's two runs plotted together -- the blue lines are a load test where the server is not paused, the green lines are where the server is paused for ~15 seconds. During that time, all requests made are delayed. While Goose is asynchronous, there were only 12 users being simulated so all the users were "hung" waiting for a response to return before making another request:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/402892/121796664-257c0480-cc1b-11eb-9568-ce818bcc0075.png">

And here it is in the percentile format like your upstream example, though a bit less granular:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/402892/121796673-404e7900-cc1b-11eb-9476-48ed369e2f50.png">

**Comment by jeremyandrews** [comment]
FWIW: the above charts are pretty much a worst-case scenario. Goose is simulating only a few "users" (12) and the test plan involves loading pages repeatedly without any pauses between requests.

Running the same test but instead with 2,500 users, and with a random pause between requests, the percentile graph does improve, as would be expected:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/402892/121847881-8c67ef00-cce9-11eb-95a7-e6aa0c725975.png">

**Comment by bbros-dev** [comment]
@jeremyandrews great to find you open to addressing 'issues'.  You're right, the first set of results confirm Goose results will be biased by CO occuring.  The second set of results are a reminder whay all empriment analysis plans need to be set out *before* the experiment is conducted - ex-post ratioanlizations are just too tempting ;)

Apart from adding some note to the docs on CO the only salient point open is: What is Goose position going forward?
From memory, some frameworks have just switched focus and focus and claim use cases where CO produces biased results are not within their scope.

I have a potential workaround in mind that might work as a quick fix - will add the the histogram issue.

**Comment by jeremyandrews** [comment]
To better explain my comment above:
 - with a low number of users and no pause between requests, the effect is exaggerated / larger
 - with a higher number of users and a pause between requests, a smaller percentage of the threads are affected by the upstream hang, so the effect is less pronounced / smaller
 - regardless, the issue is absolutely there and recognized now, thanks for bringing it to my attention
 - I do not yet have a formal plan for resolving this, and welcome learning more about your potential workaround; at minimum I'd like to add a warning/alert if/when all threads are blocked -- of course, that's just the "worst case" of this so isn't a solution
 - I'll definitely keep this issue open to get it documented, and eventually come up with a proper solution

**Comment by bbros-dev** [comment]
Thinking about this some more.  I'm less persuaded the large number of users (second case) is a mitigation.

To my mind its a variation of the argument: we simulate virtual users, and their arrival is independent of each other, this guards against CO bias.
A counter example with multiple virtual users (VU): Your infrastructure is knotted/slow/stressed VU:A has their response data being CO. VU:B arrives independently of VU:A.... so lets say it arrives after the cause of the CO of VU:A has passed.... there has been no correction or mitigation of the effect of CO on the data reported.

In fact I think the opposite would need to be true:
For multiple VUs to eliminate CO they would have to arrive in a wholy **dependent** fashion.

Specifically, lets simplify by considering a single-request per VU configuration: If you're testing 1000 req/s then each VU will have to arrive spaced 1/1000 sec apart, in order to mitigate the effects of CO.

Now the data you report from these requests is likely less subject to CO - but as soon as you relax the 1-req per VU you'll be back to reporting noise.

The need for dependent VU arrival suggests a possible quick fix for the 1-req per VU scenario.
However if you allow each VU to make more than 1-request you're back at square 1.
So VU scheduling needs to be dependent, **as well as** request scheduling by each VU also needs to be entirely dependent.

Aside from probabilistic arguments, the intuitive explanation makes sense: if you want to uncover the distribution of latency metrics you have to strip out any other randomness, other wise you'll end up reporting data that comes from some unknown mixture of distributions.
If you knew the mixing distributions (i.e. their analytic expressions) you could possibly disentangle these after the fact a report a corrected latency distribution - but here too you'd need to either know what the true latency distribution is (so would just be obtaining point estimates of its parameters - assuming it is a parametric distribution), or you'd need to know the mixture distribution (again leaving parameter estimation as the task).

I think the easier fix is to schedule VUs and their requests.

In a distributed setting this would mean you either:
1. need a message passing system (complex, but solved problem)
2. need a convention agreed among VUs as to who goes when.

**Comment by bbros-dev** [comment]
Update: We now have had a chance to look at some of the code base - we see you use NNG (ZeroMQ ante-cedant). So the foundations are in place for worker coordination and sync.

Very nice.

Look like we'll be adopting Goose, or something built on it.

**Comment by jeremyandrews** [comment]
Just an FYI: I am in the process of removing the dependence on `nng` and reworking the Manager-Worker logic on top of raw Tokio sockets, the same as the controllers are currently implemented. The underlying functionality will be the same, though this will allow me to address a number of known Gaggle (distributed loadtest) bugs and increase flexibility.

**Comment by jeremyandrews** [comment]
The impact and mitigation of Coordinated Omission in Goose is now documented in the README:
https://github.com/tag1consulting/goose/blob/main/README.md#coordinated-omission-mitigation

**Comment by bbros-dev** [comment]
Let us know if you think this should be a separate issue:

We think the output table produced under [metrics](https://github.com/tag1consulting/goose/blob/main/README.md#metrics) needs to be changed:

1. Consistency and usability:  Plotting Raw vs CO-adjusted data is aided if both tables contain the same data in the same columns.  Currently one has to parse the raw data table to get the Minimum values for CO-mitigated.
2. Measuring deviations: Currently the results always plot the std. dev. of the [averages](https://github.com/tag1consulting/goose/pull/299/commits/f0a7c2de0ddfb7a3799d413ffdcb38233f090d78#diff-9f90e93b5696724fd8e4407c9db0bfd381d5468bcfbf2f09c17ac8510a85e104R1455).  This is incorrect since you are attempting to calculate the std deviation of two data points, and the docs refer to making an inferrence that we don't think can be made from that statistic. We think the correct approach is to present a table showing the mean-absolute deviation (MAD) of the two tables: Raw and CO-mitigated (calculation is trivial `abs(raw-co)`).  

Should the minimum column always be zero in this table of MAD values? we're still thinking about that while reading the docs & code.
