### ISSUE TITLE
Doc: Percentile precision and data storage and access

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#278]
Per issue #277:

Could you document your approach to storing histogram data, specifically how you trade-off precision and speed and size.

Most useful if the analysis/description is in the context of the Dynatrace [DynaHist](https://github.com/dynatrace-oss/dynahist) ~[HDR Histrograms](http://hdrhistogram.org/) (and the [Rust implementation](https://github.com/HdrHistogram/HdrHistogram_rust)), and [possible improvements](https://github.com/HdrHistogram/HdrHistogram/issues/54)~

**Comment by jeremyandrews** [comment]
The logic in question lives in `src/metrics.rs` https://github.com/tag1consulting/goose/blob/main/src/metrics.rs#L159 : 

```rust
        // Round the time so we can combine similar times together and
        // minimize required memory to store and push upstream to the parent.
        let rounded_time = match time {
            // No rounding for times 0-100 ms.
            0..=100 => time_usize,
            // Round to nearest 10 for times 100-500 ms.
            101..=500 => ((time as f64 / 10.0).round() * 10.0) as usize,
            // Round to nearest 100 for times 500-1000 ms.
            501..=1000 => ((time as f64 / 100.0).round() * 10.0) as usize,
            // Round to nearest 1000 for larger times.
            _ => ((time as f64 / 1000.0).round() * 10.0) as usize,
        };
```

**Comment by bbros-dev** [comment]
I wonder if something like [the following](https://github.com/HdrHistogram/HdrHistogram_rust#recording-samples) isn't feasible as a near drop in replacement (at the expense of an additional crate), the last line might suffice as a quick workaround for the CO problem discussed in issue #277 :

```rust
use hdrhistogram::Histogram;
let mut hist = Histogram::<u64>::new_with_bounds(1, 60 * 60 * 1000, 2).unwrap();

// samples can be recorded using .record, which will error if the value is too small or large
hist.record(54321).expect("value 54321 should be in range");

// for ergonomics, samples can also be recorded with +=
// this call will panic if the value is out of range!
hist += 54321;

// if the code that generates the values is subject to Coordinated Omission,
// the self-correcting record method should be used instead.
// for example, if the expected sampling interval is 10 msec:
hist.record_correct(54321, 10).expect("value 54321 should be in range");
```

**Comment by jeremyandrews** [comment]
I will explore replacing the current implementation with hdrhistogram. It'll take a bit of reworking, but am intrigued to see if we can get more accurate results. I'll likely use `Histogram::<u64>::new()` instead of `new_with_bounds()` as there's no certain maximum response time and we don't want to panic if a response takes too long; of course, perhaps this can be made configurable as well.

When calling `record_correct()`, there's still the open question of what the expected sampling interval is: perhaps an average of all previous requests for that particular path ignoring the fastest and slowest outliers?

**Comment by bbros-dev** [comment]
> When calling `record_correct()`, there's still the open question of what the expected sampling interval is

From the README.md there might be a natural place to locate the workaround:

> The `--no-reset-metrics` flag tells Goose to start tracking the 10m run-time from when the first user starts, instead of the default which is to flush all metrics and start timing after all users have started

When you flush all metrics it might be an opportunity to calculate the fastest response time observed, and record that as the expected sampling interval - this would have the advantage of be conservative/prudent.  Would only know what the impact is by comparing the resulting CDF with a CDF taken prior to any changes.

HTH?

**Comment by jeremyandrews** [comment]
I'd prefer a solution that works always, whereas the above wouldn't work if `--no-reset-metrics` is enabled. Why are you proposing to use the fastest response time, instead of the average minus outliers? 

I was thinking we'd just calculate the average response time minus outliers every minute or so, and update the sampling interval each time.

**Comment by bbros-dev** [comment]
> Why are you proposing to use the fastest response time, instead of the average minus outliers?

Thinking on the fly so likely wrong ;)

We know the solution: Strip out randomness - the simplest way is to use fixed time interval between requests (irrespective of how they are generated - inter-virtual-user or intra-virtual-user).

When not implementing the solution we're making some arbitrary approximation, I think the only way you'd be able to judge 'the best' is via experiments like you conducted - except you'd need to consider the category of CO-events that have a duration smaller than the (expected) inter-arrival time.

> I was thinking we'd just calculate the average response time minus outliers every minute or so, and update the sampling interval each time.

Updating the sampling interval each time, seems to me, to move us further away from the solution which we know is a deterministic interval  (fixed being simplest) between arrivals.  If the process is ergodic we can maybe get a way with a cumulative estimate.  But now we start introducing assumptions about the underlying system as well as making your monitoring/testing process condtional on its behavior over time.

The more I think about it the more it seems that a general workaround is a bigger effort, or introduces issues that are difficult to explain of compensate for.

Maybe the workaround is to define a particular configuration Goose should be used in until a fix is in place and then code the workaround for that configuration?

Or just note CO is an issue and a fix is being implemented?

**Comment by bbros-dev** [comment]
This is drifting into implementation, and while we are not Rust Gurus we think the prospects of successful fix are very good:

1. You're using Tokio, with the `time` feature and it has the relevant functionality at hand in [`interval`](https://docs.rs/tokio/1.7.0/tokio/time/fn.interval.html) and [`interval_at`](https://docs.rs/tokio/1.7.0/tokio/time/fn.interval_at.html).  At a naive level, all that needs to happen is we record the request start-time every interval `N` and let matters proceed, as long as you record the request end-time against that start time.
2. We aren't sure how the [throttle code](https://github.com/tag1consulting/goose/blob/main/src/throttle.rs) would impact this kind of setup.

Overall, we think, the prospects for a proper fix look good - of course the devil is always in the details.

**Comment by jeremyandrews** [comment]
FWIW: I briefly explored dropping in [`HdrHistogram`](https://docs.rs/hdrhistogram) - it should live in the (recently renamed) ['GooseRequestAggregateMetric'](https://github.com/tag1consulting/goose/blob/main/src/metrics.rs#L271) but quickly ran into the following trait bounds compile-time errors:
 - `the trait bound `hdrhistogram::Histogram<u64>: std::cmp::Eq` is not satisfied`
 - `the trait `Serialize` is not implemented for `Histogram<u64>`
 - `the trait `Deserialize<'_>` is not implemented for `Histogram<u64>`

The `cmp::Eq` trait is required because we track information about many, many requests, and store them altogether in a [single HashMap](https://github.com/tag1consulting/goose/blob/main/src/metrics.rs#L109)

The `Serialize` and `Deserialize` traits are required in order to synchronize metrics from Workers to a central Manager in a [Gaggle distributed load test](https://www.tag1consulting.com/blog/show-me-how-flock-flies-working-gaggle-goose).

Per [the book](https://doc.rust-lang.org/book/ch10-02-traits.html):

> But we can’t implement external traits on external types. For example, we can’t implement the Display trait on Vec<T> within our aggregator crate, because Display and Vec<T> are defined in the standard library and aren’t local to our aggregator crate. This restriction is part of a property of programs called coherence, and more specifically the orphan rule, so named because the parent type is not present. This rule ensures that other people’s code can’t break your code and vice versa. Without the rule, two crates could implement the same trait for the same type, and Rust wouldn’t know which implementation to use.

There is a potential workaround for the Serialize/Deserialize issue documented here:
https://serde.rs/remote-derive.html

**Comment by jeremyandrews** [comment]
The hdrhistogram method for correcting coordinated omission is [documented here](https://github.com/HdrHistogram/HdrHistogram_rust/blob/master/src/lib.rs#L916):

> To compensate for the loss of sampled values when a recorded value is larger than the expected interval between value samples, this method will auto-generate and record an additional series of decreasingly-smaller (down to `interval`) value records.

The code is very simple, so it's easy to add this same logic directly to Goose's existing implementation, more or less copying this code.

There's also a comment about a post-data-collection method, but it doesn't appear to exist in the code base -- likely it's only in the upstream Java source, but still worth a quick look:

> Note: This is a at-recording correction method, as opposed to the post-recording correction method provided by `correct_clone`. The two methods are mutually exclusive, and only one of the two should be be used on a given data set to correct for the same coordinated omission issue.

**Comment by bbros-dev** [comment]
> FWIW: I briefly explored dropping in HdrHistogram ...

Yup, this is how Yaks get shaved ;)

**Comment by bbros-dev** [comment]
> The Serialize and Deserialize traits are required in order to synchronize metrics from Workers to a central Manager in a Gaggle distributed load test.

We think you'd need to work with [hdrhistogram::serialization](https://docs.rs/hdrhistogram/7.3.0/hdrhistogram/serialization/index.html), there are some examples there that *seem* to cover this sort of use case?

**Comment by bbros-dev** [comment]
> The cmp::Eq trait is required because we track information about many, many requests, and store them altogether in a single HashMap

We're not familiar enough with the Goose code base or the Rust HDRHistogram but we do wonder if the serialization, referred to in the comment above, wouldn't provide the opportunity to pass a serialized histogram.  Naively it would seem a Goose might be able to aggregate using the histogram, leaving the hash map to track data other than the response times? If you need to correlate the satte of the world couldn't the hash map hold a snapshot of the Histogram in its serialized form.

Histogram storage is very efficient, and if you fix some reasonable defaults, like whole microsecond as the unit of measurement, you could pre-define the storage without (practical) limits the maximum response time.

**Comment by jeremyandrews** [comment]
> The code is very simple, so it's easy to add this same logic directly to Goose's existing implementation, more or less copying this code.

The logic has been implemented in Goose and is documented here:
https://github.com/tag1consulting/goose/blob/main/README.md#mitigation

The back-filling is modeled after the simple HdrHistogram implementation. Each GooseUser thread is aware of its own cadence, and detects when there is a Coordinated Omission event here (and reports it to the parent thread):
https://github.com/tag1consulting/goose/blob/a15914e4fd6e7d29b9b9a95f2d970ff20d68d55c/src/goose.rs#L1567

The parent handles the actual back-filling of coordinated omission mitigation metrics (asynchronously and without affecting Goose's ability to generate load):
https://github.com/tag1consulting/goose/blob/a15914e4fd6e7d29b9b9a95f2d970ff20d68d55c/src/metrics.rs#L2274

The per-GooseUser thread cadence is calculated automatically here (it defaults to tracking the Average, but can be changed to Minimum with the `--co-mitigation` command line option):
https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1486

**Comment by bbros-dev** [comment]
We won't be able to pursue this any further.
