### ISSUE TITLE
Feature: Additional example - the internet

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#289]
This is to track an example we're thinking to add as part of becoming familiar with Goose.

In general we think you can never have too many examples, and if they become difficult to update that is a sign "Something is rotten in the state of Denmark", but not everyone shares that view....

**Comment by jeremyandrews** [comment]
PRs adding useful examples are definitely welcome. I also intend to set up a secondary repository which is more a cookbook of common patterns and helpers when writing Goose load tests.

**Comment by bbros-dev** [comment]
Closing per remark in PR
