### ISSUE TITLE
Doc: Determining when Gaggle Manager is ready

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#291]
Document how to determine when Gaggle Manager is ready.
Suspect it has to do with polling or waiting for a telnet or web socket controller to return?

We need to do this to avoid:

```bash 
failed to communicate with manager at tcp://<ip>:5115: Connection refused.
```

**Comment by bbros-dev** [comment]
Not really, we need something that blocks until the port comes online then allows the worker to run.

The controller is not Gaggle aware. That's fine.

We think something like this can be suggested in the docs: `socat - TCP4:<ip>:5115`

Thoughts? 
We have our hands and head there with some current changes so could add this just as easily.

**Comment by jeremyandrews** [comment]
There is a bug captured in #292 

In general, it is recommended you run Goose with the `-v` flag, or use the following two flags and keep an eye on the generated log file: `-g --log-file goose.log`.

A good overview of how Goose is used in production and best practices can be found here:
https://www.tag1consulting.com/blog/real-life-goose-load-testing

Also please refer to the README:
https://github.com/tag1consulting/goose/blob/main/README.md#gaggle-distributed-load-test

**Comment by bbros-dev** [comment]
Ideally, we need something that doesn't depend on an operator's attention.  As best we can tell the this is independent of #292?

**Comment by jeremyandrews** [comment]
Whoops, re-opening.

**Comment by jeremyandrews** [comment]
The current design (and documentation) requires the following:

1. start a Manager instance specifying load test parameters and how many Workers to expect 
2. start the expected number of Worker instances 
3. once all Workers are started the load test automatically starts and runs either until run time elapses (if configured) or until you ctrl-c any instance 

The Workers are not (currently) designed to start before the Manager instance. 

It’s unclear to me what additional documentation you’re asking for in this ticket, as I believe this is already documented. 

The current work on the Controller intends to make the workflow more flexible (allowing you to add/remove Workers, offering more controlling in when Workers start, etc). If your goal is to be able to start the Workers before the Manager then please create a feature request issue. (There’s already a loop when the worker starts, it just times out quickly and exits on error after 5 retries: https://github.com/tag1consulting/goose/blob/b981476734e0149d4e1c3e998c41fc3324154f7b/src/worker.rs#L70 — this could trivially be changed to loop forever or for some number of seconds/minutes)

**Comment by bbros-dev** [comment]
>If your goal is to be able to start the Workers before the Manager then please create a feature request issue.

Okay, but as an interim workaround:

We can block the worker from starting until the manager is listening.

How to do that is suitable for the documentation?

**Comment by jeremyandrews** [comment]
At this time Goose has no provision for this. It assumes you will start things in the correct order, and the Worker will time out and throw an error if you do not.

**Comment by bbros-dev** [comment]
We wanted to test that what we described in the documentation did work.... which resulted in PR #295 as an interim step.  However, that e2e test is broken by goose requiring IP addresses and not using FQDN or hostname values.  So this is blocking on the when we can test the documentated approach.

**Comment by bbros-dev** [comment]
We won't be able to pursue this. And its likely resolved by the removal of NNG in favor of the alternate implementation.
