### ISSUE TITLE
Sometimes an error status code is expected and should be considered as a success ?

### ISSUE THREAD

**Issue by jrouaix** [tag1consulting/goose#301]
Hello

I have some load scenarios expecting some 4xx http responses. They are considered as errors and output to the command line while they are, in fact, in my stories : successes.

Could we consider adding some expected_response_status: Option<StatusCode> in the request builder in order to override the behavior here : 
https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1435

I have some spare time in the next days/weeks, I should be able to contribute this one and https://github.com/tag1consulting/goose/issues/250 soon if it's ok for you ..

**Comment by jeremyandrews** [comment]
Please see the documentation here:
https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#method.set_success

We don't simply specify at compile-time, as it's possible that run-time changes are required during the test.

And of course: contributions are very welcome!

**Comment by jrouaix** [comment]
Thanks a lot ! I totally missed this one !
