### ISSUE TITLE
Remove misleading/incorrect use of std dev.

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#311]
Sorry to be so blunt, but this `util::standard_deviation(raw_average, co_average)` really has to go:

https://github.com/tag1consulting/goose/blob/fe2910a4cf57cd8a4f7844c039743a3b989017cb/src/metrics.rs#L1454

Several reasons:

1. The calculation itself has dubious/disputable claims to existence: you're estimating two moments with two data points.
2. The context in which it is used is problematic: The scalar factor for calculating 95% CI is not 1.96, etc which is the value when you have asymptotic (infinitely large) sample sizes. Making lots of assumptions you can get multipliers in the order of 12 and 60 for those 95% and 99% CI - but using those values indiscriminately (i.e. applying them) means you really would be in the realm of making stuff up.
3. There is no reasonable way to do what you want to do - automagically turn on/off CO mitigation - even as a rough approximation.
4. CO-mitigation should always be on.
5. The default 'cadence' should be the expected minimum response time.  What to do if you can't derive the expression for the expected minimum, estimate the required parameters and then calculate that expected value? A reasonable first approximation is to use the minimum value from a sample you believe is obtained from the system when it was in a healthy state.

Hopefully that is persuasive?

**Comment by jeremyandrews** [comment]
I've marked the Coordinated Omission Mitigation feature as experimental and disabled it by default in #312: I have a need for the other changes and cleanup that have been committed since the last release, and will be rolling a new release (`0.12`).  I do hope that in a future release the --co-mitigation option  can be enabled by default. (I will review/reply to your above feedback when I can.)

**Comment by bbros-dev** [comment]
> I've marked the Coordinated Omission Mitigation feature as experimental and disabled it by default in #312: 

Understand.  All progress is incremental, and things are only obvious when you understand them, and understanding takes effort which takes time and time is very scarce.

One comment I'd offer is to just do the minimum required for the CO workaround, its all the bells and whistles around inference that seem to be problematic.

Look forward to co-mitigation being turned back on.

**Comment by bbros-dev** [comment]
Closing as resolved.
