### ISSUE TITLE
Cutover README.md to Goose book

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#317]
This is the final item in the documentation refactoring to use mdbook, per issue #306

**Comment by jeremyandrews** [comment]
My preference is that we don't commit a skeleton, but actually move the README.md content into the mdbook in https://github.com/tag1consulting/goose/pull/318 -- I want to be able to see and review the actual book before it gets committed, and I don't want to commit a temporary structure that doesn't match the actual content.

**Comment by bbros-dev** [comment]
> My preference is that we don't commit a skeleton,

Nothing in the PR's restricts how you merge the PR's and in what order you do so.
If you want a big-bang release - merge the content PR's and then merge the `.github/workflow` PR. 

Let me know if something restricts you.

**Comment by jeremyandrews** [comment]
The goal isn’t a Big Bang commit. The goal is to try and keep the main branch in a deployable and usable a state. I’m happy to commit documentation that has been restructured for better discoverability. I’m also happy to discuss a WIP. 

My expectation is that the first PR to land will move some content out of the Readme and into the new book structure, with no (or absolutely minimal) other changes.
