### ISSUE TITLE
Integrating rustdoc and mdbook content

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#320]
Integrating rustdoc and mdbook.....

Currently the include directive does not work for rustdoc comments.  There is an open issue in mdbook https://github.com/rust-lang/mdBook/issues/1356. there is an open issue in cargo https://github.com/rust-lang/cargo/issues/739.

This is how safer_ffi goes about things:

https://github.com/getditto/safer_ffi/blob/5d19ae7/scripts/build_docs.sh

This is how materialize do it:

https://github.com/MaterializeInc/materialize/blob/main/bin/doc
https://github.com/MaterializeInc/materialize/blob/main/misc/doc/crates.jq

What does Goose want to do?

Perhaps its worth waiting for https://github.com/rust-lang/rust/pull/78837

At which point we can share markdown files, by [doing this](https://github.com/rust-lang/rust/pull/78837#issuecomment-729845606) in the source files?

**Comment by jeremyandrews** [comment]
Cross-referencing the documentation will certainly be handy, but is not essential at this time.

As the rustdoc is hosted at docs.rs, perhaps we can simply add valid links from the mdBook to the hosted rustdocs? (And once the mdBook is hosted in Github Pages, we can also include links back?) I understand it's preferable to be able to build and use all the documentation locally, but IMO until that's better supported it's likely not worth the headache.
