### ISSUE TITLE
NNG Usage

### ISSUE THREAD

**Issue by neachdainn** [tag1consulting/goose#33]
I saw [Jeremy's post on Reddit][1] about Goose and decided to check it out since this is the first time I get to see someone other than my use my NNG crate. Going through the code, I had a couple of minor suggestions:

1. Why is [`ACTIVE_WORKERS`][2] inside of a mutex? Being behind a mutex and atomic seems redundant when you never access it without the lock.
2. There are times when you [serialize to a buffer then immediately copy it to a `Message`][3]. You can make the code faster by directly serializing to a `Message` or cleaner by directly submitting the `Vec<u8>` to `Socket::{try_}send`.
3. You often convert the `Message` to a slice before reading deserializing from it - you should be able to directly read from the message. This won't change performance, but it might be a little cleaner.
4. The NNG crate has a [v1.0.0-rc2.2][4] which has a few minor API changes and reflect what will probably be the stable API. My "release schedule" for this crate is largely based on when I'm able to get papers submitted to conferences, so it's really only stuck as an RC because I haven't submitted anything since I pushed it.

Those suggestions aside, the main reason I'm opening this issue is that I would *love* any feedback you have on the API. I know there are a couple of people using the crate but none (until now) have code I can look through or a place where I can request feedback. I like to think I've made some solid design decisions, but I only have my personal thoughts to work off of.

One things I specifically would appreciate input on is how to handle the fact that NNG [requires a relatively new version of CMake][5] that isn't available on any of the Ubuntu LTS. If I was the only one using this code, I would just not upgrade nng-rs until something critical is needed from a newer version of NNG and I'd figure it out from there. As such, I would definitely appreciate your thoughts on how you would like to see it handled (e.g.: Is LTS support important? Are you fine with using an updated CMake?)

Thanks!
Nate

[1]: https://www.reddit.com/r/rust/comments/gqb1hh/goose_07_gains_async_for_2x_speedup/
[2]: https://github.com/tag1consulting/goose/blob/master/src/manager.rs#L38
[3]: https://github.com/tag1consulting/goose/blob/master/src/worker.rs#L246
[4]: https://crates.io/crates/nng/1.0.0-rc.2
[5]: https://github.com/nanomsg/nng#requirements

**Comment by jeremyandrews** [comment]
Thanks for the feedback, comments, and questions!

I'll review in more depth over the next few days, and try to apply all your feedback. My usage of nng isn't a performance bottleneck (Goose primarily uses nng to synchronize statistics, the actual load tests are managed locally even in a distributed test), but of course I'm happy to optimize where possible. At a quick glance, I expect to resolve 1-3 quickly (thanks), but likely will wait to address 4 until there's a new stable release, whenever that is.

My biggest confusion when I started using `nng` was not finding a way for n clients to initiate a connection to 1 server, and for that 1 server to push messages individually to any 1 of those specific clients at will. My understanding is that this is not a limitation of your crate however, but instead is the design of nng itself. I was ultimately able to work around this by having each client check in with the server regularly (pushing statistics upstream every 15 seconds).

Because of the dependency on CMake I already wrapped my usage of nng in a feature -- thus, anyone needing Gaggle support (distributed load testing) would **need** it for a really large test and IMO would be able to figure out how to install a newer version of CMake. It doesn't impact most users of Goose, who won't need distributed load testing as Goose is already respectably fast. From a single server.

As I work through your comments I'll try and provide additional feedback.

**Comment by jeremyandrews** [comment]
Regarding #1, I've removed the unnecessary Mutexes (they slipped in when I originally cleaned up some unsafe code, I appreciate the review!).

I've been unable to cleanly address #2 and #3 however, I seem to always need to start with a `Vec` and then covert it to a message for it to compile and work. Any further tips there would be greatly appreciated -- re-opening until those issues are solved.

**Comment by neachdainn** [comment]
(I didn't see this until now - sorry)

Is it the issue with serializing or deserializing? Serializing, [`Message` implements `Write`][1] so that should just work with [`serde_cbor::to_writer`][2]. Deserializing, `Message` derefs to `&[u8]` which implements `Read`, so [`serde_cbor::from_reader`][3], should work. If it doesn't, I might have assumed `Deref` will cover that case when it doesn't and I should implement `Read` directly.

[1]: https://docs.rs/nng/0.5.1/nng/struct.Message.html#implementations
[2]: https://docs.rs/serde_cbor/0.11.1/serde_cbor/fn.to_writer.html
[3]: https://docs.rs/serde_cbor/0.11.1/serde_cbor/fn.from_reader.html

**Comment by jeremyandrews** [comment]
If I try and write directly to the message (instead of to the buffer) I end up with the following error:
```
    |                                               ^^^^^^^^ the trait `std::convert::From<&nng::message::Message>` is not implemented for `nng::message::Message`
```
Trying to solve that I run into issues with ownership.

If I try and remove the calls to `as_slice()` I see the following errors:
```
    |                                                    ^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `nng::message::Message`
    |                                             ^^^ the trait `std::io::Read` is not implemented for `nng::message::Message`
```

**Comment by neachdainn** [comment]
> If I try and write directly to the message (instead of to the buffer) I end up with the following error:

It looks like you're trying to pass in a reference to the `Message`. The following compiles for me (manager.rs@429):

```rust
// Send vector of client initializers to worker.
let mut message = Message::new().unwrap();
match serde_cbor::to_writer(&mut message, &clients) {
	Ok(_) => (),
	Err(e) => {
		error!("failed to serialize client initializers: {}", e);
		std::process::exit(1);
	}
}
info!(
	"sending {} clients to worker {}",
	clients.len(),
	workers.len()
);
match server.try_send(message) {
	Ok(_) => (),
	Err((_, e)) => match e {
		Error::TryAgain => {
			if ACTIVE_WORKERS.load(Ordering::SeqCst) == 0 {
				info!("all workers have exited");
				break;
			}
		}
		_ => {
			error!("communication failure: {:?}", e);
			std::process::exit(1);
		}
	},
}
```

> If I try and remove the calls to as_slice() I see the following errors:

My bad - I forgot that I didn't `impl Read for Message`. I modeled it after `Vec<u8>`, so the following works but is really just shorthand for what you were already doing (manager.rs@250):

```rust
let requests: HashMap<String, GooseRequest> =
	serde_cbor::from_reader(&msg[..]).unwrap();
```

**Comment by neachdainn** [comment]
> I can say that NNG has been rock-solid for me -- I set up a 100-Worker Gaggle, all pushing statistics up to the Manager as fast as they can load pages, and I've never seen an error in the networking logic.

I can't take credit for anything except the safe AIO and the wrapper but I'll pass it along!
