### ISSUE TITLE
Run time flag counting user startup, even without --no-reset-metrics applied

### ISSUE THREAD

**Issue by benbrandt** [tag1consulting/goose#346]
When using large amounts of users, it appears the the run-time flag is still in effect when starting up users, even when--no-reset-metrics isn't applied.

For example, we were running a test where we had `-u 1000` and `-t 5m` where we wanted to see the load of a 1000 users over a 5 min period. However, it took longer than 5 mins to start all of the users, and test exited while only ~200 users had been started.

I bumped the `-t` flag to 30 mins to make sure there would be enough time to start all of the users, it then took 30 mins to run the test *after* all users had spun up, so it obviously wasn't the whole time of the test run.

So, it seems like the timer is in effect during user startup when it shouldn't be, but if all users have started, it correctly resets the timer. This means our time has to always be set to be a minimum of however long it takes to start up all users, which may or may not be desirable.

**Comment by LionsAd** [comment]
I agree this is confusing.

To be able to have the old behavior I think it would be best to add a `-st 5m` (startup time) flag, which by default is set to 0, which means infinite.

So the 5m and 30m scenarios would work out of the box the same: Spawn all users, then run the test for 5m / 30m.

**Comment by jeremyandrews** [comment]
I think `--startup-time TIME` mostly solves the problem, but how should `--no-reset-metrics` affect it, or should it affect it?

My general feeling is:
 - startup is always the time that it takes to launch all users, regardless of if `--no-reset-metrics` is enabled or not
 - so `--startup-time TIME` is not impacted by this flag: this timer is only relevant until all users have started
 - and `--run-time TIME` is also not impacted by this flag: this timer always starts when all users have started

**Comment by benbrandt** [comment]
I may have been unclear, but I was not using no-reset-metrics, but it still seemed to behave as if I did in terms of cancelling the run when the time limit was hit during user startup

**Comment by jeremyandrews** [comment]
@benbrandt Thanks: so from your perspective if we add a new `--startup-time TIME` flag as described above (defaulting to 0 which means no limit), and `--run-time TIME` only applies once all users are started, this solves for your use-case, correct?

In your example: startup would take ~16.5 minutes, and THEN the load test would run for 5 minutes: this is what you expect?

**Comment by benbrandt** [comment]
Yes, or at least some consistency. If I passed --run-time of 5m it seemed to start the timer after all users had been created, assuming all users were created in under 5 mins. 

If I set the --run-time to be 35 mins, all users were able to start, but then the --run-time seemed to be applied to the run time after all users were started (which meant it ended up running for an hour or so)

I guess I just expected run-time to always be inclusive of start time, or not include start-time. But it appears to be some middle-ground where depending on how many users, it sometimes includes start time, and sometimes doesn't.

**Comment by benbrandt** [comment]
Based on the docs it says
> The --no-reset-metrics flag tells Goose to start tracking the 10m run-time from when the first user starts, instead of the default which is to flush all metrics and start timing after all users have started.
Which is where I got the assumption, but maybe I have misunderstood how this works

**Comment by jeremyandrews** [comment]
Yes, there's definitely a bug here.

But in trying to find the "correct" solution I want to be sure we've thought this through. 

At this point, I think it makes sense to do as described above AND to update the documentation to remove that, as `--no-reset-metrics` will no longer affect the run time.

**Comment by jeremyandrews** [comment]
@benbrandt please re-open if you still find problems with the recent improvements made in #348.
