### ISSUE TITLE
Specify the traffic profile/shape?

### ISSUE THREAD

**Issue by PsypherPunk** [tag1consulting/goose#365]
I wanted to check: is there a way to define the "profile" of a load test?

To clarify, we're currently using Gatling, wherein you can do something like:

```scala
  setUp(scn.inject(constantUsersPerSec(500) during (1 seconds))).throttle(
    reachRps(500) in (1 seconds),
    holdFor(4),
    reachRps(10) in (1 seconds),
  ).protocols(httpConf)
```

…to have a specific traffic pattern, specifying the rate of change, for how long to hold at that rate, etc. Specifically, we need to simulate varying rates with sudden changes.

It looks like, for instance, Locust have implemented this as ["custom shapes"](https://docs.locust.io/en/stable/custom-load-shape.html).

Is there a way to achieve this in Goose?

Many thanks.

**Comment by jeremyandrews** [comment]
@PsypherPunk Unfortunately this is not yet possible with Goose. Tagging it as feature request.
