### ISSUE TITLE
error trying to connect: tcp connect error: Connection refused (os error 111)

### ISSUE THREAD

**Issue by mohammad-eb** [tag1consulting/goose#380]
when I try the load test  this error happened
error trying to connect: TCP connect error: Connection refused (os error 111)

u increase my max connections in  ubuntu
but not solved

**Comment by jeremyandrews** [comment]
What is the command you're using to start Goose? It seems that Goose is unable to connect to the web server you're trying to load test. This suggests a server or network issue, and is very likely unrelated to Goose.

**Comment by jeremyandrews** [comment]
Please re-open if you want to explore any more.
