### ISSUE TITLE
Global bearer auth

### ISSUE THREAD

**Issue by Juantamayo26** [tag1consulting/goose#383]
Is there any way to set the bearer authentication for all tasks?

![image](https://user-images.githubusercontent.com/47239906/141601644-685a7bd1-399b-48b0-acdc-75340c8530a0.png)

Some setting like:

`.set_default(GooseDefault::BearerAuth, "bearer_token")`

**Comment by jeremyandrews** [comment]
Goose is leveraging [Reqwest](https://docs.rs/reqwest/*/reqwest/index.html) to make requests, and it doesn't offer helpers for setting `bearer_auth` at the [Client level](https://docs.rs/reqwest/0.11.6/reqwest/struct.ClientBuilder.html), only at the [Request level](https://docs.rs/reqwest/0.11.6/reqwest/struct.RequestBuilder.html#method.bearer_auth).

That said, if you look at the Reqwest code, all it's doing when you call `bearer_auth()` is configuring a header:
https://github.com/seanmonstar/reqwest/blob/be8ab7b951610cbc85764198943ab053e8608454/src/async_impl/request.rs#L263

The documentation for `is_sensitive` is in the HTTP crate:
https://docs.rs/http/0.2.5/http/header/struct.HeaderValue.html#method.is_sensitive

Thus, you could manually do what you want using [`GooseUser::set_client_builder()`](https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#method.set_client_builder) to set a default header on every request (see the example).

I'm not opposed to leaving this open as a feature request though. We could look at making this configurable somehow through [`GooseUser::get_request_builder`](https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1420) which is used internally to build all requests made by the load test.

**Comment by Juantamayo26** [comment]
Thank you so much, it worked for me without problems 💯💯
