### ISSUE TITLE
How can I do a set of sequential tasks in goose

### ISSUE THREAD

**Issue by Juantamayo26** [tag1consulting/goose#395]
I'm trying to migrate some tests from Locust to Goose:

I have the following code:
![image](https://user-images.githubusercontent.com/47239906/144177841-95c5bb0e-970f-4c13-9088-9bb227263bf8.png)

How can I get data from one task to send it to another and so on..

I found this:
https://docs.rs/goose/0.15.1/goose/enum.GooseScheduler.html#variant.Serial 
But I don't know how I could do it

**Comment by jeremyandrews** [comment]
If your goal is to pass data from one task to another:

1) Is that necessary? Perhaps it's simpler to implement the logic all in a single task? (It's unclear to me what you gain splitting it into multiple tasks: unless perhaps this is important for the metrics collected?)

2) If it is necessary, then you'll need to implement Session Data:
 - https://docs.rs/goose/0.15.1/goose/goose/struct.GooseUser.html#method.set_session_data
 - https://book.goose.rs/example/session.html

3) Further, if the order tasks are executed is important, you are correct to review the scheduler configuration, perhaps better documented here:
 - https://book.goose.rs/config/scheduler.html

**Comment by Juantamayo26** [comment]
Maybe not completely necessary, I'll think about it.

There are endpoints that depend on the data of other endpoints (To be able to get C I need to do B and to do B I need to do A)

**Comment by jeremyandrews** [comment]
Were you able to figure this out? Should we close this issue?
