### ISSUE TITLE
Check if users stats for graphs are recorded in the right place

### ISSUE THREAD

**Issue by slashrsm** [tag1consulting/goose#405]
This is a followup of #394. 

We need to make sure that the user stats are recorded after the update of the counter. Not sure if this is the case at the moment so we need to make sure it is or fix it.

**Comment by slashrsm** [comment]
I checked this and confirmed that we record this metric after a user has been created and the counter has been incremented. 

The spawning/counter inc happens in `GooseAttack::spawn_attack()` and metric is recorded in `GooseAttach::sync_metrics()`, which happens later in the main program loop. 

@jeremyandrews Can we close this?

**Comment by jeremyandrews** [comment]
`sync_metrics` is invoked in several places around the code-base, and still smells like the wrong place to do this to me.

What about putting it here:
https://github.com/tag1consulting/goose/blob/main/src/lib.rs#L1711

(Before or after the call to sync_metrics doesn't matter, per your analysis, but generally it feels more logical to me to invoke this from this loop?)

**Comment by slashrsm** [comment]
Agreed, that is a more sensible place to call this.
