### ISSUE TITLE
update to tokio 1.16

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/goose#419]
When updating to tokio 1.16, the controller test fails. It seems that the tokio testing functionality may have changed, and that it's no longer properly running multi-threaded. The controller thread spins up a telnet (and/or websocket) state machine in its own thread which then makes requests against the Goose controller: with 1.16+ it seems only one of the threads runs.

**Comment by inf0rm4tik3r** [comment]
Hi, as tokio is already at 1.21.1, what is stopping goose to use the latest version of tokio?

**Comment by jeremyandrews** [comment]
It's taken me much longer to find the time to rework Gaggle support, so in order to unblock this ticket I'm going to completely disable/remove the functionality temporarily: it will get added back in a future release as soon as I have time to finish the rewrite.
