### ISSUE TITLE
write/send statistics

### ISSUE THREAD

**Issue by jeremyandrews** [tag1consulting/goose#42]
Currently Goose processes all statistics internally, and only shares them as optional running-stats during the test and a final summary at the end. With #37, client threads push raw statistics to the parent, so it's now trivial for the parent to also optionally write these statistics to a log file, or send them to a remote service.

We need to define the format of the logs written/sent. 

Locally, to start, it's enough to write to a log file in a consistent CSV format. Something like:

```
timestamp, method, url, name, response_time, status_code, success, update
```

Remotely, to start, it's enough to send logs in a consistent JSON format.

Currently threads only send `method` and `name`, we'll have to add `url` to `GooseRawRequest` so it can be included in logs.

**Comment by jeremyandrews** [comment]
What’s an example of how you’d want this to work? Just all named fields in the JSON log?

**Comment by jeremyandrews** [comment]
My thinking to send away logs is to avoid local disk io.

**Comment by nnewton** [comment]
I think you'd have local disk IO anyway though, because you would have to buffer the network connection unless you are just throwing UDP packets to the wind, unless I am missing the core concept. Also, is disk IO a foreseen throughput issue on the test truss master?

**Comment by jeremyandrews** [comment]
I will start by writing local JSON logs then, and we'll see how it goes. Note that I expect most Goose tests to be run on a single server: unlike Locust we don't need to spin of a distributed test to take advantage of available hardware. It would take at least a 44-slave Locust cluster (running on ~11 4-core vms) to generate as much load as a single Goose process running on a 4-core VM.

So yes, I expect as the test scales up, Disk IO could become an issue -- that said, we're efficiently using threads and async, so we can buffer as much as memory allows without impacting performance. That said, we can address that as a followup -- local logging is the logical place to start.
