### ISSUE TITLE
stdout metrics

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#432]
This document explains why averages are not a good metric for load testing. 
https://gatling.io/2018/11/metrics-analysis-load-testing-deviations/

Should percentiles be emitted instead?

**Comment by jeremyandrews** [comment]
In what way different than the percentiles already shown in the metrics? For example, if you look at https://book.goose.rs/getting-started/metrics.html there's a block as follows

```
 -------------------------------------------------------------------------------
 Slowest page load within specified percentile of requests (in ms):
 ------------------------------------------------------------------------------
 Name                    | 50%    | 75%    | 98%    | 99%    | 99.9%  | 99.99%
 -----------------------------------------------------------------------------
 GET /                   | 0      | 1      | 3      | 4      | 5      | 5
 GET /about/             | 0      | 0      | 3      | 3      | 5      | 5
 POST /login             | 6      | 6      | 7      | 7      | 28     | 28
 ------------------------+--------+--------+--------+--------+--------+-------
 Aggregated              | 5      | 5      | 5      | 6      | 7      | 17
 -------------------------------------------------------------------------------
```

**Comment by kazimir-malevich** [comment]
goose = "^0.15"

```
 === PER TASK METRICS ===
 ------------------------------------------------------------------------------
 Name                     |   # times run |        # fails |   task/s |  fail/s
 ------------------------------------------------------------------------------
 1: WW                    |
   1:                     |             3 |         0 (0%) |     1.00 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------
 1: WW                    |
   1:                     |      792.33 |         79 |       1,685 |         79

 === PER REQUEST METRICS ===
 ------------------------------------------------------------------------------
 Name                     |        # reqs |        # fails |    req/s |  fail/s
 ------------------------------------------------------------------------------
 GET /                    |             3 |         0 (0%) |     1.00 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------
 GET /                    |      792.33 |         79 |       1,685 |        600
```

**Comment by jeremyandrews** [comment]
Currently the percentile statistics are only displayed at the completion of the load test, but there's no reason we couldn't display them any/all times metrics are displayed. I do find the other metrics useful as well, so I wouldn't want to remove anything. Would that address your concern?

**Comment by kazimir-malevich** [comment]
That's the full test. 
https://github.com/kazimir-malevich/goose-load-test

See above for host unwrapped. 

Mean is commonly used, but percentiles during run would be good. You got median (p50) already.

**Comment by jeremyandrews** [comment]
The end-of-run statistics need to be printed (per https://book.goose.rs/getting-started/creating.html)

```patch
diff --git a/src/main.rs b/src/main.rs
index 3564ec9..b1882a6 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -12,7 +12,8 @@ async fn main() -> Result<(), GooseError> {
                 .register_task(task!(front_page)),
         )
         .execute()
-        .await?;
+        .await?
+        .print();
 
     Ok(())
 }
```

We're aware this is confusing, and will not be necessary in the next release:
https://github.com/tag1consulting/goose/pull/379

**Comment by jeremyandrews** [comment]
> If they are written to a log file in realtime, we could pick them up and maybe pipe them to a time-series db or directly to a host.

See the `--request-log`, you should be able to gather everything you need:
https://book.goose.rs/logging/requests.html

**Comment by kazimir-malevich** [comment]
I'll have a look into the logging this week, but trying to learn rust as well. The k6 site has a tonne of examples.  Kafka seems popular and I wonder if we could sit grafana on top of that. I think someone mentioned time series DBs rounding percentiles or something which is not good. Maybe we can read directly from the file and graph. What are your thoughts?

**Comment by kazimir-malevich** [comment]
I think the API needs to be as simple and intuitive as possible and some hard choices need to be made about defaults. I think the print function being one. Tests need to be clean (less cluttered) and I was also thinking about embedding a "scriptable" language as well which may garner more traction. There's a list here: https://arewegameyet.rs/ecosystem/scripting/. Though not entirely sure on this.

**Comment by jeremyandrews** [comment]
> Maybe we can read directly from the file and graph. What are your thoughts?

Current focus includes improvements to the graphs generated when running `--report-file`. If you build against the current development version of Goose, you'll see. From there the plan is to build an actual UI for controlling and viewing this information in real-time while the load test runs.

That said, enabling the `--request-log` and tailing the log it generates to feed data into an existing visualization tool could be very powerful and should be possible with what exists today.

> I think the API needs to be as simple and intuitive as possible and some hard choices need to be made about defaults.

Creating issues (and optionally PRs) with specific desired changes are welcome. Note that ALL defaults in Goose can easily be overridden in your load test:
https://book.goose.rs/config/defaults.html

> Tests need to be clean (less cluttered)

Again, please create issues with specific concerns / suggestions on cleaning up the tests. Always happy to simplify and improve, so long as we don't lose test coverage.

> I was also thinking about embedding a "scriptable" language as well which may garner more traction.

See https://github.com/tag1consulting/goose/issues/347 for some existing discussion.

> The k6 site has a tonne of examples.

For Goose examples, please see https://book.goose.rs/example/overview.html

Also see on https://book.goose.rs/example/umami.html where it refers to https://docs.rs/goose-eggs/latest/goose_eggs/ which could prove helpful to you.

**Comment by kazimir-malevich** [comment]
I will look into all of this and I apologise for taking up so much of your time.

**Comment by jeremyandrews** [comment]
No need to apologize, happy to discuss.

**Comment by jeremyandrews** [comment]
I believe everything in this issue has been addressed, please re-open if I've missed an outstanding question.

**Comment by kazimir-malevich** [comment]
I would like to thank you for all the important work you are doing here. However, my Rust journey is taking longer than I thought and I am unable to contribute as much as I'd like to.

**Comment by jeremyandrews** [comment]
I appreciate the insights you've offered! Rust is a fun journey and totally worth the effort -- enjoy it!
