### ISSUE TITLE
unrecognized option `--only-summary`

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#433]
https://book.goose.rs/getting-started/metrics.html#metrics

**Comment by jeremyandrews** [comment]
Thanks! The documentation is out of date. Goose no longer defaults to displaying metrics every 15 seconds. By default it displays metrics once all users starts, and then when the load test shuts down.

Instead, if you want running metrics, you must use the `--running-metrics` option as documented at https://book.goose.rs/getting-started/runtime-options.html

We'll update the documentation.
