### ISSUE TITLE
Task doesn't fail when status code is incorrect

### ISSUE THREAD

**Issue by d00z3l** [tag1consulting/goose#436]
Hi,

I am using GooseRequest builder and the task aren't recorded as "failed" even if an error is returned (status code 400+). The code for my task is below, in this case the JSON is invalid a 400 error is returned. Not sure if there is something wrong in how I am using it:

```rust
async fn table_data_entry(user: &mut GooseUser) -> GooseTaskResult {

    let value : u64 = rand::thread_rng().gen_range(245..255);
    let data = TableUpdate::new(&vec!["2000-01","LAX","JFK","AA", "N126AA", "Flight Time"], value as f64);

    let req = user.get_request_builder(&GooseMethod::Patch, "api/end-pont")?
        .basic_auth("admin", Option::<&str>::None)
        .json(&data);

    let req = GooseRequest::builder()
        .set_request_builder(req)
        .build();

    user.request(req).await?;

    Ok(())
}
```

I have put together a fix to return the error and also return the body as part of the error message (goose.rs 1631-1638):

```rust
       if !request_metric.success {
            if let Ok(r) = response {
                warn!("{:?} {}: {}", &path, &request_metric.error, r.text().await.unwrap_or("".to_string()));
            } else {
                warn!("{:?} {}", &path, &request_metric.error);
            }
            return Err(GooseTaskError::RequestFailed{raw_request: request_metric});
        }
```

I can create a pull request if this solves the issue I have.

**Comment by d00z3l** [comment]
The error is in the request log see below. The error does appear in the per request numbers and in the "ERRORS" section in the end. This issue that the error doesn't show up in the per task details and an error isn't logged to the console when the error occurs. Logging to the console seems important to me because as I can see that something is failing, maybe because on an incorrect task. See details below. 

```
{"coordinated_omission_elapsed":0,"elapsed":57000,"error":"400 Bad Request: ","final_url":"http://localhost:5050/api/end-point","name":"","raw":{"body":"","headers":["(\"authorization\", Sensitive)","(\"content-type\", \"application/json\")"],"method":"Get","url":"http://localhost:5050/api/end-point"},"redirected":false,"response_time":1,"status_code":400,"success":false,"update":false,"user":21,"user_cadence":0}
```

```
 === PER TASK METRICS ===
 ------------------------------------------------------------------------------
 Name                     |   # times run |        # fails |   task/s |  fail/s
 ------------------------------------------------------------------------------
 9: table_data_entry      |
   1:                     |             2 |         0 (0%) |     0.04 |    0.00
 -------------------------+---------------+----------------+----------+--------
 Aggregated               |            12 |         0 (0%) |     0.21 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------

 9: table_data_entry      |
   1:                     |        4.50 |          1 |           8 |          1
 -------------------------+-------------+------------+-------------+-----------
 Aggregated               |        1009 |          1 |       4,046 |         40

 === PER REQUEST METRICS ===
 ------------------------------------------------------------------------------
 Name                     |        # reqs |        # fails |    req/s |  fail/s
 ------------------------------------------------------------------------------
 GET                      |            12 |      2 (16.7%) |     0.21 |    0.04
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------
 GET                      |        1009 |          1 |       4,046 |        280
 ------------------------------------------------------------------------------
 Slowest page load within specified percentile of requests (in ms):
 ------------------------------------------------------------------------------
 Name                     |    50% |    75% |    98% |    99% |  99.9% | 99.99%
 ------------------------------------------------------------------------------
 GET                      |    280 |  2,000 |  4,000 |  4,000 |  4,000 |  4,000

 === ERRORS ===
 ------------------------------------------------------------------------------
 Count       | Error
 ------------------------------------------------------------------------------
 3             GET : 400 Bad Request:
 ------------------------------------------------------------------------------
 ------------------------------------------------------------------------------
```

**Comment by jeremyandrews** [comment]
In the current release you must include `-v` to see errors etc on the console. A PR was already merged so this will not be required in the next release. When you enable `-v` do you see the error?

**Comment by d00z3l** [comment]
It is hard to tell as the -v logs everything to the console including debug statements so it is very hard to find errors. Should the per task metrics include the failure count?

**Comment by jeremyandrews** [comment]
Which version of Goose are you using? If a single `-v` is logging everything then you must be using the latest development version? With the current stable release a single `-v` should only show INFO level logs and higher. It would take two `-vv` to log debug messages too. (A PR was recently committed as not showing `INFO` level messages by default was proving confusing to new users.)

In any case, I reviewed the code in question and we don't seem to be emitting an `info!()` level message when detecting an invalid HTTP response code as I thought. I agree we should, a PR is welcome. Perhaps we'd check if `request_metric.error` is not empty, and if so print the error as an INFO level message, around here:
https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1630

**Comment by jeremyandrews** [comment]
> Should the per task metrics include the failure count?

In order for a task to show as an error, you must return Err() from your task. Per-request errors will only show up in the per-request section of the metrics.

**Comment by d00z3l** [comment]
I was using 0.15.2 but are on the current main branch. info, warn or error? I also find it helpful to include the request body as in this case and others the issue is often caused by invalid payload. Example code in the location use suggested:

```rust
if !request_metric.success {
	if let Ok(r) = response {
		warn!("{:?} {}: {}", &path, &request_metric.error, r.text().await.unwrap_or("".to_string()));
	} else {
		warn!("{:?} {}", &path, &request_metric.error);
	}
	return Err(GooseTaskError::RequestFailed{raw_request: request_metric});
}
```

**Comment by d00z3l** [comment]
> In order for a task to show as an error, you must return Err() from your task. Per-request errors will only show up in the per-request section of the metrics.

So I should be doing `user.request(req).await?.response?;` in the task?

**Comment by jeremyandrews** [comment]
It sounds like you're looking for the [debug log](https://book.goose.rs/logging/debug.html). Try adding the following options:
`--debug-log debug.log`

Now review the `debug.log` to find complete details about all request errors, including the request made, the response headers, and the response body. (Unfortunately due to [this reqwest limitation](https://github.com/tag1consulting/goose/issues/336) we are frequently unable to log all request headers.)

You can also store the body of the request made in the request log if you enable [`--request-body`](https://book.goose.rs/logging/requests.html?highlight=request-body#request-log).

**Comment by jeremyandrews** [comment]
> So I should be doing user.request(req).await?.response?; in the task?

Take a look at the provided Goose examples. You need to decide what qualifies as a failure of your task.  For example, see the [`drupal_memcache`](https://book.goose.rs/example/drupal-memcache.html) example and how it calls [set_failure](https://docs.rs/goose/latest/goose/goose/struct.GooseUser.html#method.set_failure) when various expectations aren't met. 

For much simpler error handling, see the [`simple`](https://book.goose.rs/example/simple.html) which simply passes errors up.

**Comment by d00z3l** [comment]
I think the [session](https://github.com/tag1consulting/goose/blob/main/examples/session.rs) sample needs to be updated, that is what I started with. It doesn't check the response so the task will always succeed even if it fails.

```rust
/// A very simple task that simply loads the front page.
async fn authenticated_index(user: &mut GooseUser) -> GooseTaskResult {
    // This will panic if the session is missing or if the session is not of the right type.
    // Use `get_session_data` to handle a missing session.
    let session = user.get_session_data_unchecked::<Session>();

    // Create a Reqwest RequestBuilder object and configure bearer authentication when making
    // a GET request for the index.
    let reqwest_request_builder = user
        .get_request_builder(&GooseMethod::Get, "/")?
        .bearer_auth(&session.jwt_token);

    // Add the manually created RequestBuilder and build a GooseRequest object.
    let goose_request = GooseRequest::builder()
        .set_request_builder(reqwest_request_builder)
        .build();

    // Make the actual request.
    user.request(goose_request).await?;

    Ok(())
}
```

**Comment by d00z3l** [comment]
The simple example also doesn't check for the response error so the task will always succeed.

**Comment by jeremyandrews** [comment]
Mostly correct. It will fail if `request()` returns an `Err()`. 

There's a number of lines where this function many return an Error:
- https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1497
- https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1508
- https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1520
- https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1623
- https://github.com/tag1consulting/goose/blob/main/src/goose.rs#L1628

As [explained in the documentation](https://book.goose.rs/example/simple.html), the `simple` example is by-design as simple as possible (and clones a similar example from Locust), just showing basic interactions with the Goose library. It is very much not intended to demonstrate all possible Goose functionality or best practices.

For a more fleshed-out example, see the ['umami`](https://github.com/tag1consulting/goose/tree/main/examples/umami) example. See the ['umami documentation'](https://book.goose.rs/example/umami.html), the [`related blog`](https://www.tag1consulting.com/blog/goose-clouds-load-testing-scale), and the [`goose-eggs version`](https://github.com/tag1consulting/goose-eggs/tree/main/examples/umami).

**Comment by d00z3l** [comment]
The issue with the examples (simple and session) is that the request could fail because of a typo or invalid payload and the task will be marked as successful. 

From the task how do you actually check for an error? I just checked `user.request(req).await?.response?` and it doesn't work because the response is actually Ok when the status is 400+ or different to `expect_status_code`. I would have though the request will return an error if the status code is different to the what is expected.

In my case I am trying to get the simplest example working. I did that by copying the sample and going from there. When I provided the wrong JSON for the payload of the task it wasn't obvious that it failed because it was saying it succeeded. I only knew it failed because I wasn't getting an incorrect log statement in my back-end.

This isn't criticism, I just want to understand how to use it better because it works great, I am able to send 100s of request with very little overhead which is awesome.

**Comment by jeremyandrews** [comment]
Tasks and Requests are different things. (It may be helpful to see this PR which is working to clarify this https://github.com/tag1consulting/goose/pull/435.

In Goose, there are Requests of which one or more are contained in a Task of which one or more are contained in a TaskSet. It is up to you when writing your load test to determine if a single failed Request results in the entire Task failing or not.

For example: if you have a Task called "load front page" it may 1) load index.html, 2) validate the HTML title and returned Headers, 3) scrape locally hosted assets from the returned html, and 4) load each of those scraped assets (ie images, JS and CSS). It's common for one or more of these assets to be missing (resulting in a 404) or otherwise to generate an error: but even though that Request failed I would consider the Task to have failed.

When writing load tests with Goose, I always enable the [error log](https://book.goose.rs/logging/errors.html) and the [debug log](https://book.goose.rs/logging/debug.html) to collect as much information as possible about errors. This will capture all 400+ responses (unless you override this, ie if you WANT to load test a 404 page) and allow you to quickly track down things like typos.

Of course, if you Really want a 1:1 mapping between a single Request and a single Task, you can do this easily enough by parsing the [`GooseResponse`](https://docs.rs/goose/latest/goose/goose/struct.GooseResponse.html) that's returned by, for example, a [get Request](https://docs.rs/goose/latest/goose/goose/struct.GooseUser.html#method.get) and returning an Err() from your Task if the Status Code isn't what you expect.

I referred you to the Umami example as it is the most complete load test example included with Goose and demonstrates how to do things like this and much more. I personally tend to leverage the Goose Eggs validate functions to avoid writing boilerplate.

**Comment by jeremyandrews** [comment]
It's a little outdated now, but we tried to capture some real-world examples of using Goose in this blog:
https://www.tag1consulting.com/blog/real-life-goose-load-testing

**Comment by jeremyandrews** [comment]
Please also see this similar discussion: https://github.com/tag1consulting/goose/issues/437

**Comment by d00z3l** [comment]
It would be good to be able to easily return an error from a request if the status is invalid. In my case I am testing an API not a web page.  Something like:

```rust
let req = user.get_request_builder(&GooseMethod::Post, "api/view/Flight/execute")?
        .basic_auth("admin", Option::<&str>::None)
        .json(&view);

let req = GooseRequest::builder()
        .set_request_builder(req)
        .error_on_fail()
        .build();
```

Is that something you would consider?

**Comment by jeremyandrews** [comment]
Yes, adding flexibility is always welcome, so long as it doesn't negatively impact performance. This would be a welcome addition.

**Comment by jeremyandrews** [comment]
Fixed in https://github.com/tag1consulting/goose/pull/438
