### ISSUE TITLE
assert HTTP status code from goose request?

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#437]
Are we not supposed to assert HTTP status codes from a Goose request and just view the **status_codes** in the metrics from the config?

**Comment by jeremyandrews** [comment]
You can see [validate_and_load_static_assets()](https://docs.rs/goose-eggs/latest/goose_eggs/fn.validate_and_load_static_assets.html) for an example of how to work with this: 
https://github.com/tag1consulting/goose-eggs/blob/main/src/lib.rs#L780

**Comment by kazimir-malevich** [comment]
Should we be retrieving static elements which would  be hosted on a CDN? Wouldn't we just want to validate our system? I was thinking if we made a POST and received 200 that would be seen as a pass.

And also I'd be reticent to have a function that contains 'and' as a function should just do one thing.

We could add an error message on Err() couldn't we and I was thinking of the HTML status code and not  the HTML response as a string?  But my thinking may be incorrect and confused.

**Comment by jeremyandrews** [comment]
There are many ways and things to load test. One of the purposes of load tests is to test assumptions: launches can go very badly if in fact the CDN isn't properly configured or if things are flushed too frequently etc. We often leverage Goose to validate our assumptions. That said, Goose is a framework so it's up to you if it just validates the response codes or more.

The linked function is part of a helper library called [Goose Eggs](https://docs.rs/goose-eggs/latest/goose_eggs/), and solves a direct need we have which is to load an HTML page AND then also all contained "static" elements (many of which may actually be dynamically generated). The AND function joins several smaller functions from the Goose Eggs library that can instead be called individually if desired, but this can result in a lot of boilerplate in your load test.

The HTML status code is one of MANY things that Goose can (and does) validate. In some cases you can blindly trust the response code, but it's not uncommon to receive say a 200 OK that is actually a Load Balancer error message, etc. So it's critical that Goose can also validate Headers, Cookies, HTML Titles, and arbitrary text (including JSON) returned by the request. See [goose_eggs::ValidateBuilder](https://docs.rs/goose-eggs/latest/goose_eggs/struct.ValidateBuilder.html) for a list of things we frequently validate in load tests to be sure things are working as we believe.

**Comment by kazimir-malevich** [comment]
That was a good answer.
