### ISSUE TITLE
[Doc Update] No GooseDefault::DebugFile 

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#462]
[config](https://book.goose.rs/config/defaults.html)

Has a **GooseDefault::DebugFile** associated method, but it's probably been removed in the **GooseDefault enum**. We now have **DebugLog** and **DebugFormat**. I am running yesterday's crates.

**Comment by kazimir-malevich** [comment]
https://github.com/tag1consulting/goose/pull/463/
Not sure, why the conflicts?

**Comment by kazimir-malevich** [comment]
https://github.com/tag1consulting/goose/pull/465

**Comment by jeremyandrews** [comment]
Fixded by #465
