### ISSUE TITLE
Panic when shutting down via controller

### ISSUE THREAD

**Issue by slashrsm** [tag1consulting/goose#474]
Connected to an idle test via the Telnet controller and did:

```
goose> start
load test started
goose> stop
load test stopped
goose> shutdown
load test shut down
goose> Connection closed by foreign host.
```

Which resulted in 

```
thread 'main' panicked at 'internal error: entered unreachable code: there shouldn't be a step after finished', src/metrics.rs:2689:25
```

The test obvioulsy still did shut down, but it is not nice to do so with a panic :).

**Comment by jeremyandrews** [comment]
Are you able to duplicate with the latest code? I'm testing this now and am seeing a clean shutdown when repeating the steps you listed above.

**Comment by slashrsm** [comment]
Yes I am still getting the same error, except that it is on line 3056:25 now. I started the test on `drupal_memcache` example with the following options `-u 10 -r 3 -t 60 --report-file report.html --no-reset-metrics --no-autostart`.
