### ISSUE TITLE
Feature: adaptive hatch function: control connection life-time and "burst" behavior

### ISSUE THREAD

**Issue by diefans** [tag1consulting/goose#488]
I don't know if this is easy possible with current goose...

I would like to test a typical scenario, where lots of users "storm" the service at certain times (rush hours e.g. students start their courses in the morning, while on the weekend/evening usage drops) - there are lots of new connections/clients requesting service APIs. So I would like to simulate the creation of new connections - something like an adaptive hatch function, where you can define connection life-time and burst behavior: `f(runtime) -> [ConnectionWithLifetime, ...]`

If this is already possible, I would appreciate any example or comment.

**Comment by jeremyandrews** [comment]
Two options currently exist. 

You can pre-create a test-plan (see the bottom example):
https://book.goose.rs/getting-started/test-plan.html

Or you can use the controller to adjust the load ok the fly (again scroll to the bottom):
https://book.goose.rs/getting-started/test-plan.html

**Comment by diefans** [comment]
thanks
