### ISSUE TITLE
get_current_url validator

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#503]
We have a **redirect** validator which takes a boolean, but I wondered if we need, or if it is possible, to have a **get_current_url** validator, so we can determine if redirection has actually taken us to the URL, we'd expect?

**Comment by jeremyandrews** [comment]
You can find this in the [GooseRequestMetric](https://docs.rs/goose/latest/goose/metrics/struct.GooseRequestMetric.html#structfield.final_url).
