### ISSUE TITLE
breaking change on a minor upgrade

### ISSUE THREAD

**Issue by arnauorriols** [tag1consulting/goose#507]
First of all, thanks a lot for this project! It's wonderful. Just an small heads-up that I've experienced a versioning issue, that I assume stems from the fact that Cargo is not entirely semver compliant with regards to pre-1.0 versions. While semver states that any change is a breaking change before 1.0, cargo's default "caret semantics" [state that](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility):
> Versions are considered compatible if their left-most non-zero major/minor/patch component is the same

In my particular case, I have some code depending on `goose: 0.16.0` that was using `GooseUser::channel_to_parent`, which has been renamed to `GooseUser::metrics_channel` in 0.16.2.

**Comment by jeremyandrews** [comment]
That was definitely a mistaken oversight, I'm really sorry for that! We should have incremented to `0.17` with that change.

The commit in question is https://github.com/tag1consulting/goose/pull/477/files#diff-8905444b55b06af46eab00f6c46432e4906b5f422270d89a3f3d650a94822071 -- we should have incremented the major version.

**Comment by jeremyandrews** [comment]
Closing ticket, will aim to be more careful of this with future releases.
