### ISSUE TITLE
use rust to set the exec script is too diffcult, compared to  k6, suggest use js.

### ISSUE THREAD

**Issue by heliping** [tag1consulting/goose#527]
use rust to set the exec script is too diffcult, compared to  k6, suggest use js.
https://github.com/grafana/k6

**Comment by jeremyandrews** [comment]
Can you please clarify your request? Goose is written in Rust, are you suggesting it should be re-written in JavaScript? Or are you saying something else?

**Comment by heliping** [comment]
k6----> golang + js     
it can write js script for testcase, but convert js to golang, and use golang to execute the testcase.
its performance is very nice.
I think use rust to write the testcase is too difficult.
The user need to be familiar with rust.

**Comment by slashrsm** [comment]
The part of Goose is the fact that it is written in Rust to utilize language-level advantages. We have no plans to rewrite it into so other language.
