### ISSUE TITLE
[Question] How can I get my own debug logs?

### ISSUE THREAD

**Issue by lukehsiao** [tag1consulting/goose#536]
Just starting with Goose and working on a simple login scenario, following the examples. I'm running into a tokio panic when trying to `user.get_session_data_unchecked`, but I'm unsure why. 

I'd like to add some debug prints or logs, but it's not clear to me how to actually get that output with Goose. Could someone give me some pointers?

**Comment by jeremyandrews** [comment]
First, I recommend not using the _unchecked variation as that will panic if something is not right. Possibly you can look at the backtrack for full details. 

Logging can be read about here:
 https://book.goose.rs/logging/overview.html
 
Specifically you’d be able to use the debug log:
https://book.goose.rs/logging/debug.html

Development specific docs are here:
https://docs.rs/goose/latest/goose/logger/index.html#writing-debug-logs

**Comment by lukehsiao** [comment]
Perfect, thanks!
