### ISSUE TITLE
getting hyper debug/trace logs

### ISSUE THREAD

**Issue by lcmgh** [tag1consulting/goose#550]
Hi!

I would like to see the debug/trace logs hyper is emitting. Is there a way to get it somehow?

`RUST_LOG=hyper=debug` has not worked.

Thanks

**Comment by jeremyandrews** [comment]
You can enable `-v` to see DEBUG logs while running a load test, and this includes hyper debugging. (Use `-vv` if you want TRACE level logs, too.)

Alternatively, you can enable `-gg -G goose.log` if you want to save the logs to a file (in this case named `goose.log`). (Use `-ggg` if you wan the log file to include TRACE level logs.)

In all cases, Trace level logging is extremely noisy and will negatively impact performance.
