### ISSUE TITLE
Non friendly for newcomers

### ISSUE THREAD

**Issue by alexdyukov** [tag1consulting/goose#563]
Hello!

As an NON rust developer i cannot understand how i can use `goose`:
1) no links for docker hub or something, but Dockerfile exists
1.1) tag1consulting user https://hub.docker.com/u/tag1consulting has no images for goose
1.2) tons of "goose" images in https://hub.docker.com/search?q=goose&operating_system=linux&type=image but no for http testing tool, but "golang migration tool" with same name
2) no binary builds in github or github build workflows, which means "i cannot download ready-to-use software"
3) no user instructions
3.1) no instructions in README.md
3.2) no makefile/bash scripts or instructions "how to build this software"
3.3) no examples, except ofc some cargo commands at official site, which focus on rust developers only

**Comment by jeremyandrews** [comment]
1) There is no generic Dockerfile for Goose. What was there was something we had temporarily used when recording https://www.tag1consulting.com/blog/how-load-test-goose-part-3-bigger-instances and has now been removed to minimize confusion

2) Goose is a library, not an application. There is no binary to download, as load tests must be written in Rust and then compiled.

3) I've rewritten the [README](https://github.com/tag1consulting/goose/blob/main/README.md) to be more friendly to newcomers, without becoming redundant with other existing documentation. If you still want to try Goose, start with the Goose Book at https://book.goose.rs/. You will need to write Rust code.

**Comment by alexdyukov** [comment]
Ye, i got misunderstand with README.md by `Goose is a highly efficient load testing TOOL crafted in [Rust](https://www.rust-lang.org/),`

Thanks for reply!
