### ISSUE TITLE
User Context

### ISSUE THREAD

**Issue by thisilike** [tag1consulting/goose#570]
### Is there some way to give the user Context?
I can't seem to find anyway to get context into the transaction function.
It would be nice to have some kind of context for the Scenario,Transaction and User.

**To explain my problem:**
I want to load test an API, to make the request the API takes some parameters that can't be generated, but need to be picked from a pool of options. This pool is about 200k lines in a csv but it is problematic to open the file in every transaction, especially when it would end up with multiple hundred/thausand open files on the system so it would be nice to give the scenario the pool or each user an option etc.

**Comment by jeremyandrews** [comment]
There's a variety of methods you could use. For your specific use-case, you may want to explore setting a [`OnceCell`](https://doc.rust-lang.org/std/cell/struct.OnceCell.html) prior to invoking `GooseAttack::initialize` which you can then read within specific transactions when needed.

You could also [a session](https://docs.rs/goose/latest/goose/goose/struct.GooseUser.html#method.get_session_data) if you need per-user customizations.

**Comment by thisilike** [comment]
Thx. Seems like I overlooked it

**Comment by jeremyandrews** [comment]
Great! Feel free to re-open this, or open a new issue if you run into problems implementing it.
