### ISSUE TITLE
compile on windows failed

### ISSUE THREAD

**Issue by ActivePeter** [tag1consulting/goose#572]
<img width="841" alt="image" src="https://github.com/tag1consulting/goose/assets/8100696/f3647c47-d03c-47a1-bae6-04c439a4ee59">
Seems tokio version need to be updated

**Comment by jeremyandrews** [comment]
Are you able to test updating Tokio, to confirm it solves your problem? I don't currently have a Windows server to test on, but I'll fix that shortly.

**Comment by ActivePeter** [comment]
I switched to rust 1.67.1 and then it's ok
