### ISSUE TITLE
Programatically accessing the HTML Report

### ISSUE THREAD

**Issue by buck06191** [tag1consulting/goose#593]
We have a use case where it would be useful to access the HTML report from within the Rust code itself - we would like to upload it to S3 from inside a regular Fargate task each time it runs. It would be nice to use the AWS SDK to do this where we can generate the report and then when the load test is done, run the code to upload to S3. 

The alternative is to chain some scripts together inside docker which is doable but not as nice.

Is there already a way to access this kiond of functionality, or is it something that needs to be done through an alternative approach?

**Comment by jeremyandrews** [comment]
Goose will write logs and reports locally. If you want it to write directly to S3, you'd have to mount S3 on a local mountpoint and then have Goose wrirte there. What we typically do, however, is use a simple shell-script wrapper which copies any/all artifacts to whatever desired permanent storage when the load test finishes.

**Comment by buck06191** [comment]
Grand, I think that's the approach we'll take then. I just wanted to make sure there wasn't anything in the library itself as well. Thanks!
