### ISSUE TITLE
how to log response body 

### ISSUE THREAD

**Issue by JimFuller-RedHat** [tag1consulting/goose#596]
is there a built in way to log response bodies ?

**Comment by JimFuller-RedHat** [comment]
and while I am asking ... how to use GooseDefault::LogLevel

**Comment by jeremyandrews** [comment]
> is there a built in way to log response bodies ?

Response bodies are only logged to the debug log (if this is not disabled), and that's in the case of error. For more detail see:

- https://docs.rs/goose/latest/goose/goose/struct.GooseUser.html#method.log_debug
- https://book.goose.rs/logging/debug.html

You could duplicate this logic to log all responses, if desired. Or perhaps you could even simply log succesful responses to your requests using the debug log.

> and while I am asking ... how to use GooseDefault::LogLevel

The general idea is documented here:

- https://docs.rs/goose/latest/goose/config/trait.GooseDefaultType.html
- https://book.goose.rs/config/defaults.html for examples.

**Comment by JimFuller-RedHat** [comment]
ah right, I wanted to log valid responses ... I guess we can use goose egg to validate (feel free to close this)

**Comment by jeremyandrews** [comment]
It's definitely possible, but not the typical use case so not done by default.
