### ISSUE TITLE
is it possible to pass paths programatically?

### ISSUE THREAD

**Issue by JordiPolo** [tag1consulting/goose#76]
Probably this is not really an issue but really my inability with Rust.

I have[ a project ](https://github.com/JordiPolo/minos)that reads from an openapi file to generate tests. I thought I could integrate performance tests also via Goose.

First I create the main structs needed
```rust
    let mut configuration = GooseConfiguration::default();
    configuration.hatch_rate = 1; 
    configuration.host = config.base_url.clone();
    let goose_attack = GooseAttack::initialize_with_config(configuration);
    let mut task_set = taskset!("ExampleTasks");
```

This works. BY THE WAY, although there is a default of 1 for hatch_rate in the GooseConfiguration struct, somehow I needed to set it manually to 1 to make it work.

Then in my codebase I have a loop where I execute against every path specified in the openapi spec, I want to pass the path, it would look like this:
```
for path in paths {
        let task = GooseTask::new(move |s| std::boxed::Box::pin(website_with_path(s, &path))));
        task_set = task_set.register_task(task);
}

goose_attack
    .register_taskset(
        task_set)
    .execute();
```

And it almost works. If instead of passing path to the task, I pass `""`, it works. But with path there is a complain that the closure does not map the function signature.

As I said, probably is my inability with Rust, I'm clueless on how to pursue. 
Still I thought it would be useful to write an example on how to do this as I would imagine programmatically setting paths should be a common case.
I am willing to write a minimal example once I can make it work.

**Comment by jeremyandrews** [comment]
What about loading the paths in the task itself, instead of trying to pass it into the task?

ie, instead of hard coding the path "/" here:
https://github.com/tag1consulting/goose/blob/master/examples/simple.rs#L50

Instead load one or more paths from your file?

**Comment by LionsAd** [comment]
I think you need another closure that has a function signature of `func(c: GooseClient)`.

I would first create the closure (and move the path inside it).

Then you pass this closure to task! and it should work unless I miss something.

**Comment by JordiPolo** [comment]
Thanks for the quick responses!

@jeremyandrews there's a lot of computation between reading the original files and getting the callable urls with proper variables filled in. The only way would be have them somewhere accessible by the task. 

@LionsAd  Not 100% sure of what you meant but if you meant this:
```rust
        let my_c =  |client: &GooseClient |  async {  client.get(&path); };
        let task = task!(my_c);
```
I tried and got:
```
   = note: expected fn pointer `for<'r> fn(&'r goose::goose::GooseClient) -> std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = ()> + std::marker::Send + 'r)>>`
                 found closure `[closure@/Users/jordi/.cargo/registry/src/github.com-1ecc6299db9ec823/goose-0.7.5/src/goose.rs:272:24: 272:68 my_c:_]`
```

**Comment by JordiPolo** [comment]
[This answer](https://stackoverflow.com/questions/52696907/why-does-passing-a-closure-to-function-which-accepts-a-function-pointer-not-work) may be relevant.
Maybe there needs to be some change in `GooseTask::new` to make it able to use a closure?

**Comment by jeremyandrews** [comment]
What about writing paths into a `lazy_static` wrapped in a RwLock (so it can be shared between multiple goose users)?

For example, assuming the following `Cargo.toml`

```rust
[package]
name = "pathlist"
version = "0.1.0"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"

[dependencies]
goose = "0.8"
lazy_static = "1.4.0"
```

You could load all your paths from a lazy_static as follows:

```rust
use goose::prelude::*;
use lazy_static::lazy_static;
use std::sync::RwLock;

lazy_static! {
    static ref PATH_LIST: RwLock<Vec<String>> = RwLock::new(Vec::new());
}

fn build_list_of_paths() {
    let mut path_list = PATH_LIST.write().unwrap();
    // Do expense stuff here, pushing paths into PATH_LIST
    path_list.push("/foo".to_string());
    path_list.push("/bar".to_string());
    // ...
    path_list.push("/one/54321/two".to_string());
}

fn main() {
    // do expensive stuff first
    build_list_of_paths();

    GooseAttack::initialize()
        .register_taskset(taskset!("PathTest")
            .register_task(task!(load_paths))
        )
        .execute();
}

async fn load_paths(user: &GooseUser) {
    let path_list = PATH_LIST.read().unwrap().clone();
    for path in path_list {
        user.get(&path).await;
    }

}
```

You could of course get much fancier, ie you could shuffle the vector, and/or you could create different vectors and process each with a different task function, etc.

(You could also use `.test_start` to invoke `load_paths` from `GooseAttack` if you need/want a `GooseUser` object in that function, and it'll still be called one time as a load test setup function.)

**Comment by JordiPolo** [comment]
Thanks so much, it does work and now I have [integrated Goose into my application](https://github.com/JordiPolo/minos/commit/fccf9738cb8c0936087de533983f8fcd2d1ae806#diff-04c58b4a25c148b317bbd61e8059d897R1-R52) (polishing to come next).
I think this can be closed then?

**Comment by jeremyandrews** [comment]
That's great!

Let's leave this open for now, as I aim to explore ways to simplify passing in a URL.

**Comment by LionsAd** [comment]
@JordiPolo I found a way:

```
  let path = "/foo";
    let my_c:Box<dyn for<'r> FnOnce(&'r GooseClient) -> Pin<Box<dyn Future<Output = ()> + 'r>>> = Box::new(move |client| Box::pin(async move {  
      client.get(path);
    }));

    let task = GooseTask::new(my_c);
```

should in theory work even right now.

Can you try?

**Comment by LionsAd** [comment]
Okay we should really define a type:

```
type GooseTaskFunction = for<'r> fn(&'r GooseUser) -> Pin<Box<dyn Future<Output = GooseTaskResult> + Send + 'r>>;
```

```
    let path = "/foo";
    let my_c:GooseTaskFunction = Box::new(move |client| Box::pin(async move {
      client.get(path).await?;
    }));
    let task = GooseTask::new(my_c);
```
except we don't box goose task functions right now, but maybe that still works. Testing ...

**Comment by LionsAd** [comment]
No - okay - we need to Box our functions, but then it should work.

**Comment by LionsAd** [comment]
Here is an example how to do that @JordiPolo:

https://github.com/tag1consulting/goose/pull/126/files
