### ISSUE TITLE
Make it possible to rate limit a loadtest to x req/s

### ISSUE THREAD

**Issue by LionsAd** [tag1consulting/goose#90]

**Comment by jeremyandrews** [comment]
General implementation may be something like this:
 - new option such as `--throttle-reqs=` accepting integer value (or do we want a float?)
 - if enabled, set up a new bounded channel between the parent (sender) and the user threads (receivers)
 - the bound of the channel will be the specified throttle-reqs value (ie, 100)
 - when enabled, the parent adds a new permission-object into the bounded channel every 1000/throttle-reqs milliseconds (using the same logic as hatch rate)
 - when enabled, each GooseUser must first grab a permission-object from the bounded channel before making any request
 - if the bounded channel is empty, the GooseUser blocks

When starting a Goose Load Test you'd still need to configure the # of users, the hatch rate, etc -- this would just prevent the load test from ever making more than the maximum number of requests per second.

**Comment by LionsAd** [comment]
Plan looks good to me 😊

**Comment by jeremyandrews** [comment]
The standard [mpsc channels](https://docs.rs/tokio/*/tokio/sync/mpsc/index.html) won't work, as this stands for Multi-Producer-Single-Consumer, the opposite of what we want to do.

There's the [spmc library](https://docs.rs/spmc/*/spmc/index.html) which is Single-Produce-Multi-Consumer, but it doesn't support bounded channels.

The [broadcast channel](https://docs.rs/tokio/*/tokio/sync/broadcast/fn.channel.html) is nearly what we want, but it doesn't implement `clone()` and instead has a custom subscribe() method (clone is needed by `GooseUser`).

There's [crossbeam channel](https://docs.rs/crossbeam/*/crossbeam/channel/fn.bounded.html) which looks like it would work, but it's not async so blocked GooseUser's would prevent other threads from running.

Finally there's [async-channel](https://docs.rs/async-std/*/async_std/sync/fn.channel.html) which seems to meet all our necessary criteria: bound channel, multi-consumers, implements clone.

**Comment by jeremyandrews** [comment]
The downside to `async-channel` is it's marked as an `unstable` feature in the `async-std` library.
